// Разрешаем конфликты между System.Windows.Forms и WPF в пользу WPF-типов.
// Этот файл необходим из-за UseWindowsForms=true (нужен для NotifyIcon в трее).
global using Application = System.Windows.Application;
global using Binding = System.Windows.Data.Binding;
global using Brushes = System.Windows.Media.Brushes;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using Color = System.Windows.Media.Color;
global using ComboBox = System.Windows.Controls.ComboBox;
global using ContextMenu = System.Windows.Controls.ContextMenu;
global using Cursor = System.Windows.Input.Cursor;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using Label = System.Windows.Controls.Label;
global using ListBox = System.Windows.Controls.ListBox;
global using MessageBox = System.Windows.MessageBox;
global using MenuItem = System.Windows.Controls.MenuItem;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Orientation = System.Windows.Controls.Orientation;
global using ProgressBar = System.Windows.Controls.ProgressBar;
global using RadioButton = System.Windows.Controls.RadioButton;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using TextBox = System.Windows.Controls.TextBox;
global using Timer = System.Windows.Threading.DispatcherTimer;
global using ToolTip = System.Windows.Controls.ToolTip;
global using TreeView = System.Windows.Controls.TreeView;
